Feature/okubo phase1 2
ut-klab-ygroup/Operantbox_development pull request #4
Opened 2024-06-03 12:28 UTC by takayoshio

すみません、google docsの方確認いただいてもよろしいでしょうか？
解決ずみ課題の項目の冒頭にファイル変更内容として記入しています。

2024-06-25 12:21 UTC, Mebuki-mebuki requested changes
delay_stateとnose_poke_stateについてコードを確認してコメントしました。ご確認ください。

2024-06-25 12:21 UTC, Mebuki-mebuki commented on src/operant_conditioning_task/states/nose_poke_state.py
> +        if not nose_poke_correct_time_list or (self.results['nose_poke_time'] - nose_poke_correct_time_list[-1]) >= 3:
not nose_poke_correct_time_list はリストが空という条件のことだと思いますが、空リストがFalseとして判断されるのはpythonの仕様としては正しいのですが、コードの意図が伝わりづらいのでlen(nose_poke_correct_time_list) == 0 と書くのが適切かと思います。

2024-06-25 12:21 UTC, Mebuki-mebuki commented on src/operant_conditioning_task/states/nose_poke_state.py
> +            self._give_reward()
NPを検出した場合にもともとのプログラムではreward_stateに移行して次のトライアルに移行してたかと思うのですが、このプログラムでは3秒おきに何度もNPできるようになってるかと思うのですが、それは正しいですか？
また,_give_rewards()は中で1秒程度のsleepが入りますが、そもそもこの関数はタイマーのシグナルハンドラの中で使われていて、一般的にシグナルハンドラで時間のかかる処理をするのは不適切なので、reward()の呼び出し方を考えた方が良いかと思います。

2024-06-25 12:21 UTC, Mebuki-mebuki commented on src/operant_conditioning_task/states/nose_poke_state.py
> +                if sensor.is_pressed:
_で始まる要素は外部に公開していないということを意図しているので、_task_gpioの_nose_poke_sensorsにアクセスするのは不適切です。
また109行目のelseの段階でis_nose_pokedがFalseだと思うのですが、111行目でis_pressedがTrueになることはあるのでしょうか？

2024-06-25 12:21 UTC, Mebuki-mebuki commented on src/operant_conditioning_task/states/nose_poke_state.py
> +                    self.results['selected_index'] = self._task_gpio._nose_poke_selected_index
↑と同様に_nose_poke_timeと_nose_poke_selected_indexにアクセスするのは不適切です。
またtask_gpioではこれらの値はis_nose_pokedがTrueに更新されるときのみ更新しているので、意図した値が得られていないのではないかと思います。

2024-06-25 12:21 UTC, Mebuki-mebuki commented on src/operant_conditioning_task/states/nose_poke_state.py
> +                        time.sleep(0.001)
#correct timeの登録より先に行うと、NPの間中loopをしてしまうため注意
とtime.sleep(0.001)の意味がぱっと見よくわかりませんでした。
説明があると助かります。

2024-06-25 12:21 UTC, Mebuki-mebuki commented on src/operant_conditioning_task/states/nose_poke_state.py
> +        if self._task_gpio._lick_sensor.is_pressed:
_check_nose_poke()でreset_state()を行ってしまっているのでis_lickedが読めなくなっているのかと推察しますが、reset_state()を行うのを後回しにしてここではis_lickedを使うのが良いと思います。

2024-06-25 12:21 UTC, Mebuki-mebuki commented on src/operant_conditioning_task/states/nose_poke_state.py
> +            self._task_gpio._lick_time = time.time()
_lick_timeを外部からアクセスするべきではないです。またこれは必要ない気がしますが必要ですか？

2024-06-25 22:53 UTC, takayoshio commented on src/operant_conditioning_task/states/delay_state.py
> +        #phase_settings.delay_state_skip:
はい。

2024-06-25 22:54 UTC, takayoshio commented on src/operant_conditioning_task/states/delay_state.py
> +            self.call_counts_list.append(-1)
動作観察がしやすいなと思ったんですが、変数でいいと思います。

2024-06-25 22:57 UTC, takayoshio commented on src/operant_conditioning_task/states/delay_state.py
> +        while time.perf_counter() - start_time <= wait_time:
ありがとうございます。
つまり、85行目　if time.perf_counter() - start_time > wait_time:#phase_settings.wait_time_in_s:
と役割が重複していていらないということですよね？

2024-06-25 22:58 UTC, takayoshio commented on src/operant_conditioning_task/states/delay_state.py
> +            signal.signal(signal.SIGALRM, handler)
了解です。__init__の中にしてみます。

2024-06-25 22:59 UTC, takayoshio commented on src/operant_conditioning_task/states/delay_state.py
> +        while time.perf_counter() - start_time <= wait_time:
修正済

2024-06-25 23:00 UTC, takayoshio commented on src/operant_conditioning_task/states/delay_state.py
> +            signal.signal(signal.SIGALRM, handler)
修正済

2024-06-25 23:00 UTC, takayoshio commented on src/operant_conditioning_task/states/delay_state.py
> +    def _give_reward(self):
どうすると綺麗か何かアイデアはありますか？

2024-06-25 23:01 UTC, takayoshio commented on src/operant_conditioning_task/states/delay_state.py
> +        if call_count == self.lick_detect_hz*5:
変数にしました。
すみません、ここは昨日直したところだったのでコメントまで追いついてませんでした。
修正済

2024-06-25 23:04 UTC, takayoshio commented on src/operant_conditioning_task/states/delay_state.py
> +        if call_count == self.lick_detect_hz*5:
すみません、ここは昨日直したところだったので、コメント追いついていなかったです。
一応変数にしておきます。
修正済

2024-06-25 23:11 UTC, takayoshio commented on src/operant_conditioning_task/states/delay_state.py
> +        if time.perf_counter() - start_time > wait_time:#phase_settings.wait_time_in_s:
意識します。

2024-06-25 23:11 UTC, takayoshio commented on src/operant_conditioning_task/states/delay_state.py
> +                self._task_gpio.reset_state(self.name)
元のプロトコルは無視で大丈夫です。

2024-06-25 23:13 UTC, takayoshio commented on src/operant_conditioning_task/states/nose_poke_state.py
> +        self.NP_detect_hz=20
元々、lickは10hz検出可能な一方で、npは４hzあたりからチャタリングっぽい挙動がありました。その中でそれぞれ少しでも高い頻度で検出したいという意図でしたが、NPセンサーの接続が問題だったようで、昨日からは今のところ両方20hzで検出できています。この箇所は、この状態が続けば不要になります。

2024-06-25 23:17 UTC, takayoshio commented on src/operant_conditioning_task/states/nose_poke_state.py
> +        if current_time - start_time > phase_settings.stimulus_duration_in_s:
-1ってdebugの時でしたっけ。報酬無限状態？いずれにしても現状のプロトコルでは不要かもしれません。

2024-06-25 23:17 UTC, takayoshio commented on src/operant_conditioning_task/states/nose_poke_state.py
> +            self.results['state_result'] = TaskResult.Success
現状のプロトコルでは全てsuccessとして進めたいです。

2024-06-26 01:12 UTC, takayoshio commented on src/operant_conditioning_task/states/nose_poke_state.py
> +            if call_count % (self.lick_detect_hz/self.NP_detect_hz) == 0:
はい。そういうことにならないように気をつけるというのが大事かなと思います。一応整数倍にならなかったらエラーが出るようにはしておきます。

2024-06-26 01:12 UTC, takayoshio commented on src/operant_conditioning_task/states/nose_poke_state.py
> +            if call_count % (self.lick_detect_hz/self.NP_detect_hz) == 0:
対応済

2024-06-26 01:16 UTC, takayoshio commented on src/operant_conditioning_task/states/nose_poke_state.py
> +    def _give_reward(self):
どういうアイデアがありますか？

2024-06-26 01:38 UTC, takayoshio commented on src/operant_conditioning_task/states/nose_poke_state.py
> +        target_num = self._settings.NOSE_POKE_TARGETS[self.results['selected_index']]
ここはちょっとややこしいですが、NPholeにはそれぞれ、以下の3つが割り当てられています。
①ラズパイ上のピンの番号
②gpio上で処理されるindex
③NPhole番号
①と②の対応は、gipo.pyの _nose_poke_callbackでされています。①と③の対応は、settings.pyのNOSE_POKE_TARGETS でされています。
流れとしては、gipo.pyの _nose_poke_callbackにて、反応したピン番号のindexが②として取られ、これが、settins.py上のNOSE_POKE_TARGETSではどの番号に対応しているかを、処理しているのが、このnose_poke_states.py上の_nose_poke_callback_phase2のtarget_numを得る一連の処理で行われています。

2024-06-26 01:41 UTC, takayoshio commented on src/operant_conditioning_task/states/nose_poke_state.py
> +        target_num = self._settings.NOSE_POKE_TARGETS[self.results['selected_index']]
出力上は、左から?右から?NPholeの番号を0,1,2,3,4,5としたいが、ピンの番号の登録は、それと反対の向きになっているために複雑な実装になっています。

ただまあ、gpio.py上のpin assignmentを逆順にしたらどちらかで良くなるでしょうか？
この場合、nose_poke_ledsとnosepoke_sensorsは両方変更した方がよろしいでしょうか。

2024-06-26 01:41 UTC, takayoshio commented on src/operant_conditioning_task/states/nose_poke_state.py
> +        target_num = self._settings.NOSE_POKE_TARGETS[self.results['selected_index']]
わかりづらければすみません。とりあえずtarget_numというのは微妙なので、その命名は変えておきます。

2024-06-26 01:44 UTC, takayoshio commented on src/operant_conditioning_task/states/nose_poke_state.py
> +        if not nose_poke_correct_time_list or (self.results['nose_poke_time'] - nose_poke_correct_time_list[-1]) >= 3:
ありがとうございます。対応済みです。

2024-06-26 01:45 UTC, takayoshio commented on src/operant_conditioning_task/states/nose_poke_state.py
> +            self._give_reward()
前者は前のプロトコルなので考えなくて大丈夫です。

なるほど、1秒間持続させたいのですが、どうしたら良いでしょうか。

2024-06-26 01:53 UTC, takayoshio commented on src/operant_conditioning_task/states/nose_poke_state.py
> +                if sensor.is_pressed:
ラズパイのButton ライブラリーには、is_pressedとwhen_pressedというものがあり、前者は、センサー反応中にTrueになり、後者は、センサーが押され始めた時に信号を伝えるもののようです。

https://www.denshi.club/parts/2021/05/gpiozero13import-mcp3001mcp3002mcp3004mcp3008.html

is_nose_pokedは、gpio.pyを見ていただいたらわかりますが、when_pressedに対応してTrueになる今回のtask_gpio.py独自のフラグです。

is_nose_pokedは、when_pressedに対応して、押され始めでTrueになり、その後reset_state()が実行されると、Falseになります。is_nose_pokedは最初のオサレはじめしか検出できず、センサー反応があり続けているのか、それとも、その後すぐにセンサー反応が消えたのかわかりません。
これが持続的なセンサー入力に対応するということの意味です。

2024-06-26 03:29 UTC, takayoshio commented on src/operant_conditioning_task/states/nose_poke_state.py
> +                        time.sleep(0.001)
nose_poke_hole_number_correct_list.append(self.results['nose_poked_hole_num'])を_give_rewardより先に行うと、おそらく_give_rewardの中で1秒間sleepしていることもあるのかもしれませんが、correct_listへの登録が遅れて、if節の要件が満たされてしまうということです。

time.sleep(0.001)は意図不明なので削除しておきます。

2024-06-26 03:35 UTC, takayoshio commented on src/operant_conditioning_task/states/nose_poke_state.py
> +                        time.sleep(0.001)
後ほどどういう現象であったか再度確認します。

2024-06-26 03:37 UTC, takayoshio commented on src/operant_conditioning_task/states/nose_poke_state.py
> +                if sensor.is_pressed:
task_gpio.py内部での使用しか想定されていなかった関数をその外で使用する必要が生じたため、命名を変更する必要があるということについては、理解しました。修正しておきます。

2024-06-26 03:40 UTC, takayoshio commented on src/operant_conditioning_task/states/nose_poke_state.py
> +                    self.results['selected_index'] = self._task_gpio._nose_poke_selected_index
_の問題については前述のとおりです。

self.results['nose_poke_time']については、前の行のtime.time()で値を更新させているので意図した値が得られています。
その次の行のself.results['selected_index'] = self._task_gpio._nose_poke_selected_indexについては、おっしゃるとおり、意図した値が得られていませんが、これについては、その以下のコードで用いていないものでした。紛らわしくて申し訳ありません。削除しておきます。

実際のNP_hole_numberについては、それ以下のコードで得ています。

2024-06-26 03:41 UTC, takayoshio commented on src/operant_conditioning_task/states/nose_poke_state.py
> +                    self.results['selected_index'] = self._task_gpio._nose_poke_selected_index
修正ずみ

2024-06-26 03:48 UTC, takayoshio commented on src/operant_conditioning_task/states/nose_poke_state.py
> +            self._task_gpio._lick_time = time.time()
_の問題については前述のとおりです。

2024-06-26 03:50 UTC, takayoshio commented on src/operant_conditioning_task/states/nose_poke_state.py
> +            self._task_gpio._lick_time = time.time()
is_lickedを用いて、reset_stateを用いる場合には、不要ですが、is_pressedを用いて、lickの時間を記録するためには、必要です。

2024-06-26 03:52 UTC, takayoshio commented on src/operant_conditioning_task/states/nose_poke_state.py
> +        if self._task_gpio._lick_sensor.is_pressed:
is_lickedの使用を取りやめた理由をうまく言語化/記録していなかったので、そこは整理してみようと思います。

ざっくりいうと、is_lickedのフラグは、元々1stateで一度のlickやNPを検出するようにできており、複数検出には向いていなかったようにも思います。is_lickedを使うと、0.1秒ごとに毎回reset_state()を行う必要が生じて、動作が重くなり?orチャタリング的な現象が生じて(?),うまく検出できていなかったと記憶しています。

それか、nosepokeとの混線を懸念したか、いずれにしても、曖昧なのでこの辺りはきちんと整理したいと思います。

2024-06-26 04:01 UTC, takayoshio commented on src/operant_conditioning_task/states/nose_poke_state.py
> +            self._give_reward()
とりあえずcall_countを用いることをやってみます。

2024-06-26 07:44 UTC, takayoshio commented on src/operant_conditioning_task/states/delay_state.py
> +            signal.signal(signal.SIGALRM, handler)
start_timeを引き受けていたので、initの中には今のところできていません。start_timeをmonitorのスタートではなく、delay state全体のstart_timeとすればできますかね。

2024-06-29 03:44 UTC, takayoshio commented on src/operant_conditioning_task/states/nose_poke_state.py
> +            self._task_gpio._lick_time = time.time()
修正しました。

2024-06-29 03:45 UTC, takayoshio commented on src/operant_conditioning_task/states/nose_poke_state.py
> +        if self._task_gpio._lick_sensor.is_pressed:
is_licked, is_nose_pokedはいずれも持続検出ができないことが問題です。持続検出をするためにis_pressedを使うことにしました。

2024-06-29 03:45 UTC, takayoshio commented on src/operant_conditioning_task/states/nose_poke_state.py
> +        if self._task_gpio._lick_sensor.is_pressed:
修正済みです。

2024-06-29 03:46 UTC, takayoshio commented on src/operant_conditioning_task/states/delay_state.py
> +    def _give_reward(self):
model.pyの中にrewardを制御するclassをおいて、それをmodelのclassに引き受けさせることで解決しました。

2024-06-29 03:47 UTC, takayoshio commented on src/operant_conditioning_task/states/nose_poke_state.py
> +                if sensor.is_pressed:
_で始まる要素が外部で用いられることのないように、修正しました。

2024-06-29 03:47 UTC, takayoshio commented on src/operant_conditioning_task/states/delay_state.py
> +            signal.signal(signal.SIGALRM, handler)
ここのみ未対応です。

2024-07-11 03:28 UTC, takayoshio commented on src/operant_conditioning_task/states/nose_poke_state.py
> +                        time.sleep(0.001)
当時のコードではgive rewardの実行に0.5秒程度かかってしまっていたため、先に、次のhandlerが呼び出されてしまうというバグが起きていました。それが原因です。
これらは対応済みです。

2025-01-10 14:49 UTC, merged

2025-01-10 14:52 UTC, takayoshio commented
@Mebuki-mebuki すいません、あまり読まずにmergeしてしまいましたが、よかったでしょうか。必要あればrevertします。